### ISSUE TITLE
Syntax highlight with Pigments

### ISSUE THREAD

**Issue by okelet** [fralau/mkdocs_macros_plugin#10]
Thanks for this plugin! I am using it with the macro code_from_file [mentioned in this issue](https://github.com/mkdocs/mkdocs/issues/692#issuecomment-427056366) and the [Material theme](https://squidfunk.github.io/mkdocs-material/), but I can't make them work together with syntax highlight, the file is shown, but without any colors. The source code differs when using the macro:

```html
<pre><code class="xxx">mycode
```

But when using direct code blocks, it generates HTML like this:

```html
<div class="codehilite"><pre><span></span><span class="p">{</span>
```
Any idea how to solve this?

**Comment by fralau** [comment]
I am not exactly sure I understand what you wish to do. 
To include another file, maybe you want to use the plain jinja2 {%include 'filename' %} directive?

**Comment by WithHolm** [comment]
hey, 
i had the same issue, however i fixed it by defining code fence in the markdown file and inside that codeblock, define `{% include 'codefile.ps1' %}` 

``` markdown
``` Powershell
{% include 'test.ps1' %}
` `` 
```

**Comment by fralau** [comment]
Thanks @WithHolm . Anyone would have objections against closing this issue?

**Comment by okelet** [comment]
OK for me, thanks all for your help!
