### ISSUE TITLE
access theme template html from macro

### ISSUE THREAD

**Issue by alanlivio** [fralau/mkdocs_macros_plugin#121]
Hi. 
The mkdocs-macros works great when using templates inside the docs folders. 
But I use mkdcos-material and want to include some templates from it inside my index.md.
More precisely, I want to use the [social.html](https://github.com/squidfunk/mkdocs-material/blob/master/material/partials/social.html) template.
So, inside my index.md I used
```
{% include "partials/social.html" %}
```
But I receive the following error:
```
get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: partials/social.html
```
How to proceed?
Best regards.

**Comment by alanlivio** [comment]
@fralau, may you help me with this one?
Thank you since now.

**Comment by fralau** [comment]
Hi @alanlivio, mkdocs-macros is about markdown, and has no influence on mkdocs templates (HTML). You might have to post your query on the appropriate location (presumably mkdocs-material).

**Comment by alanlivio** [comment]
Thanks @fralau. Done at [here](https://github.com/mkdocs/mkdocs/issues/2759).
