### ISSUE TITLE
{% for ...} loop creates line breaks

### ISSUE THREAD

**Issue by alanlivio** [fralau/mkdocs_macros_plugin#126]
The following code with indented lines generates break lines between macros elements
```
{% for social in config.extra.social %}
  {% set icon = social.icon.replace('/','-') %}
  :{{icon}}: [{{ social.title }}]({{ social.link }})&nbsp;&nbsp;
{% endfor %} 
```

![image](https://user-images.githubusercontent.com/604808/154352115-3bbd2547-5eb6-4d98-9ceb-f876e3f91958.png)

The desired behavior works online contatenation

```
{% for social in config.extra.social %}{% set icon = social.icon.replace('/','-') %}:{{icon}}: [{{ social.title }}]({{ social.link }})&nbsp;&nbsp;{% endfor %} 
```
  
![image](https://user-images.githubusercontent.com/604808/154352161-f26afee2-a413-43e7-a999-81109a29e975.png)

**Comment by eyllanesc** [comment]
try changing `{%` and `%}` to `{%-` and `-%}`, respectively.

**Comment by fralau** [comment]
@eyllanesc Spot one: mkdocs-macros uses the standard Jinja2 templating engine. That feature is documented under [Whitespace Control](https://jinja.palletsprojects.com/en/3.0.x/templates/#whitespace-control).

**Comment by alanlivio** [comment]
Thank you both @eyllanesc and @fralau. The `%-`  worked. The issue can be closed.
