### ISSUE TITLE
Reference variables defined in mkdocs.yml directly inside macro

### ISSUE THREAD

**Issue by ryandaugherty** [fralau/mkdocs_macros_plugin#13]
This is probably not an issue so much as a question from a very junior programmer. How do you reference variables defined in the mkdocs.yml directly inside macro code without passing them in as a parameter? I can define a variable inside mkdocs.yml under 'extra', reference it in the template, and pass it in as a parameter in the macro function, but I'd rather just directly reference that variable in the macro code rather than pass it in. I tried a bunch of ways to do this but couldn't get the context... 

Thanks much! Your macro plugin is awesome and just the thing I needed for what we wanted to do with our docs.

**Comment by fralau** [comment]
Thanks for the appreciation!

I am not sure I fully understand what you mean by "How do you reference variables defined in the mkdocs.yml directly inside macro code without passing them in as a parameter? " 

Could you give an example of what you wish to do?

**Comment by ryandaugherty** [comment]
Thanks for the response! 

I have an "env" variable in my mkdocs.yml: 

`extra: 
    price: 1000
    env: accountx`

Then in my Markdown template I'm calling a python macro function, passing in env and a dictionary; the function simply switches text based on what the env value is. 

`## Conditional Text based on the 'env' variable in mkdocs.yml
{{ switchText(env, { 

"accounta": "
!!! note
    This note is specific to the accountA documentation variant
", 

"accountb": "
This text represents the accountB docs variant!
", 

"accountx": "
This text represents the **AccountX** docs variant!
"

}) 
}} `

Here is the main.py with my macro: 

`def declare_variables(variables, macro):
    """
    This is the hook for the functions

    - variables: the dictionary that contains the variables
    - macro: a decorator function, to declare a macro.
    """
    
    @macro
    def switchText(currentEnv, textDictionary):
        for x in textDictionary:
            if currentEnv == x: 
                return textDictionary[x]
        return "Environment value for conditional text not found!" `

I works, but I would like to simplify it a bit by NOT passing the env variable as a parameter into the python macro. Instead, I would like to directly reference the env variable defined in mkdocs.yml. I tried a bunch of stuff from the jinja2 docs but nothing seemed to work.

Thanks!

**Comment by fralau** [comment]
Wow. This is elaborate stuff! I understand your point and it is food for thought.

For the time being, this is how I would work around this: if we have an issue of writing several functions that all access an environment (or "namespace"), then perhaps an object will do it.

Here is a hint, though I have not tried it in this instance: there should be no problem if you create a class, and use @macro decorator on its methods (so if you have the `foo` object as an instance, then you would have a macro `foo.switchText(textDictionary)`.

Once the object is instantiated, and the currentEnv property is set (via a macro?), then the methods (each of which could be a macro) will be able to access that property.

**Comment by ryandaugherty** [comment]
Ah perfect thanks! I knew it was something simple like that I was missing. Previously I had been trying to assign `variables` with its own values (above the macro), but didn't realize it was overwriting the global context. Also I'm pretty new to Python so I didn't know about the underscores vs CamelCase. Here's my new function: 

```
    @macro
    def switch_env_text(text_dictionary):
        for x in text_dictionary:
            if variables["env"] == x: 
                return text_dictionary[x]
        return "Environment value for conditional text not found!" 
```
Thanks again for responding to this, and also thanks for merging that pull request for making includes work. Very helpful!
