### ISSUE TITLE
How to access a env variable?

### ISSUE THREAD

**Issue by xrow** [fralau/mkdocs_macros_plugin#142]
{{ git.tag }} was not working for me inside a gitlab pipeline but outside...

My idea was to access a env var instead, but I did not know how. I read a couple of sources on the internet but nothing worked for me. Maybe you can include a howto in the docs.

**Comment by fralau** [comment]
Also from the shell?

**Comment by xrow** [comment]
There is no warning or else in the cli just the confirmation that is is loading

`DEBUG    -  [macros] - Variables: ['extra', 'config', 'environment', 'plugin', 'git', 'generator', 'social', 'consent']
`

**Comment by xrow** [comment]
Acutally for the git.tag thing I opened https://github.com/fralau/mkdocs_macros_plugin/issues/143

**Comment by fralau** [comment]
What is the situation of this issue?
