### ISSUE TITLE
{{ git.tag }} will not render tag 3.0.0-beta5

### ISSUE THREAD

**Issue by xrow** [fralau/mkdocs_macros_plugin#143]
{{ git.tag }} will display 3.0.0 if the last tag is 3.0.0-beta5.

I think there are many ways to fix this. Here is one idea.

```
[root@localhost helm-ezplatform]# git describe --tags
3.0.0-beta5-12-gfb09168
[root@localhost helm-ezplatform]# git tag --list | sort -V | tail -n1
3.0.0-beta5
```

**Comment by fralau** [comment]
It is true that the code is cutting the last part.  Is it truly necessary?

The question is whether that behavior would be requested by all users?

Please argue pro or con.

**Comment by xrow** [comment]
Sorry it is just a a bug on how the string is parsed. There should be no pro con needed. :-)

I just wanted to report it.

**Comment by fralau** [comment]
That cut looks arbitrary to me; that was my own idea, but I don't see any compelling reason for keeping it.

**Comment by fralau** [comment]
Let me know if that fixes it for you?
