### ISSUE TITLE
Incompatibility with mkdocs-material footer

### ISSUE THREAD

**Issue by rolouis** [fralau/mkdocs_macros_plugin#146]
Is it possible to disable the use of the "extra" tag?
It looks like the mkdocs-macros plugin affects the configuration values provided for the footer in mkdocs-material.
See: https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/

BR

**Comment by rolouis** [comment]
E.g. make this variable https://github.com/fralau/mkdocs_macros_plugin/blob/8d1e9e494e43e18d200ced02ad613b54244277b2/mkdocs_macros/plugin.py#L516

configurable

**Comment by fralau** [comment]
Hi, I am lacking a little context. From your observation, how does the macro plugin affect the footer? Would you like to disable the extra variable, or make it configurable?

**Comment by fralau** [comment]
No news, closing.
