### ISSUE TITLE
'navigation' Object not containing enough page information.

### ISSUE THREAD

**Issue by niklasfink** [fralau/mkdocs_macros_plugin#156]
Hi, I wanted to use the [`navigation` (or `files`) object](https://mkdocs-macros-plugin.readthedocs.io/en/latest/pages/#batteries-included-default-objects) to get page information of sub pages.

With this, I want to build a rich overview page of all sub-pages including some of their meta data. The function would be similar to the [Excerpt Macro in Confluence](https://confluence.atlassian.com/doc/excerpt-macro-148062.html).

Another example (to try to explain the goal of this) would be building an index of all sub-pages within a specific folder. For this, you need the Title of the page and the URL and can the build a link. However, at the moment, I don't see how this should work.

### Issue
The `pages` (List[Page]) within the `navigation` object neither contain the Title of a page, nor any meta data in most cases. It seems like they only contain this information the further down in the directory tree they are.

### Jinja Template Example
````
{% for page in navigation.pages if page.parent.title == "Folder1" %}
    Title: {{ page.title }} // URL: {{ page.url }} // Meta: {{page.meta.metavar|default('None')}}
{% endfor %}
````

### Pictures
In the following picture, we only get the details of File0 (the current page) and the other pages don't show any detail infos, except the URL.
![image](https://user-images.githubusercontent.com/1809301/226623904-1c016cfa-fff3-4128-ba4e-cd47b14fc285.png)

In the next picture, we have it working as expected. The details of all sub-pages of Folder1 are retrieved.
![image](https://user-images.githubusercontent.com/1809301/226624348-7e542c79-da9f-4db0-9527-736ad7c2f11d.png)

What's the issue here or how can this be done differently? From my perspective, `navigation.pages` should have the same content, independent to where it is used in the file tree.

**Comment by fralau** [comment]
Hello, I believe you could do that. But this would be more a mkdocs issue wouldn't it? 

https://www.mkdocs.org/dev-guide/themes/#config

**Comment by fralau** [comment]
@niklasfink  Is it still an issue?

**Comment by niklasfink** [comment]
I don’t think this is generally solved, but I also don’t know whose responsibility it would be to implement this.
I worked around it by modifying the rendering queue.

**Comment by fralau** [comment]
Some ideas:

- Keep into account that the navigation is being built _while_ mkdocs is rendering the pages, unless you defined your page structure in the config file (`mkdocs.yaml`). So when you are rendering the first page, the second and third have not been read yet.
- Confluence's macros are rendered at runtime, _after_ the navigation has been calculated.
- So if you want to make an equivalent of the Excerpt macro, either you work with a complete navigation when the page is being rendered, or... you need a second pass. Which might not be easy to implement, on a static website.

It seems to me that the question should be asked to the [mkdocs](https://github.com/mkdocs/mkdocs) team?
