### ISSUE TITLE
Deprecation Warning: pkg_resources

### ISSUE THREAD

**Issue by niklasfink** [fralau/mkdocs_macros_plugin#157]
When serving/building mkdocs with the macros plugin enabled:

INFO     -  DeprecationWarning: pkg_resources is deprecated as an API
              File "/usr/local/python/3.11.2/lib/python3.11/site-packages/mkdocs_macros/context.py", line 19, in <module>
                import pkg_resources
              File "/usr/local/python/3.11.2/lib/python3.11/site-packages/pkg_resources/__init__.py", line 121, in <module>
                warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)

**Comment by fralau** [comment]
This might be an issue with python 3.11? 🤔

**Comment by johnthagen** [comment]
I'm getting this warning even on Python 3.10

```
nox > mkdocs serve
INFO     -  DeprecationWarning: pkg_resources is deprecated as an API
              File "lib/python3.10/site-packages/mkdocs_macros/context.py", line 19, in <module>
                import pkg_resources
              File "lib/python3.10/site-packages/pkg_resources/__init__.py", line 121, in <module>
                warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
```

### Environment

- Python 3.10.11

```
mkdocs                     1.4.2
mkdocs-htmlproofer-plugin  0.13.1
mkdocs-macros-plugin       0.7.0
mkdocs-material            9.1.7
mkdocs-material-extensions 1.1.1
mkdocs-video               1.5.0
```

**Comment by johnthagen** [comment]
The replacements:

- New in Python 3.7: https://docs.python.org/3/library/importlib.resources.html
- New in Python 3.8: https://docs.python.org/3/library/importlib.metadata.html

Given that [Python 3.7 is end of life in just two months](https://endoflife.date/python) I would recommend bumping the minimum supported Python to 3.8 here:

https://github.com/fralau/mkdocs_macros_plugin/blob/e8e0356a2983c1f0604a4fba021c718e80cc011d/setup.py#L43

And then replace usages of `pkg_resources` with `importlib` from the standard library.

**Comment by fralau** [comment]
This warning should be solved. Could you please test if that work for you?

(that will also be an opportunity to test if version 1.1.0-alpha works for the rest)

**Comment by fralau** [comment]
@johnthagen This is excellent!
