### ISSUE TITLE
parse jinja templates on non-markdown pages

### ISSUE THREAD

**Issue by spettinichi** [fralau/mkdocs_macros_plugin#160]
I have a project where I store sample source files so users can clone the repository and run them as is, but I also want to embed them into markdown pages for usage with mkdocs as well. I followed this to be able to embed the source files https://mkdocs-macros-plugin.readthedocs.io/en/latest/tips/#i-would-like-to-include-a-text-file-from-line-a-to-line-b
This works great, except that variables in the source files will not be evaluated and replaced.

I don't see a way to accomplish this. I believe I will have to add variable parsing within my python file, but this plugin does not have a function to pass a variable and have it evaluated by jinja rules and return the result, so it seems I would have to duplicate much of the functionality of this plugin which is not ideal. 

Is there something I am missing, or is this something of interest to include into the project?

**Comment by spettinichi** [comment]
I ended up getting this working and submitted a PR for the changes to the documentation page linked above
https://github.com/fralau/mkdocs_macros_plugin/pull/161

**Comment by fralau** [comment]
Thanks! Would this work for you?
https://mkdocs-macros-plugin.readthedocs.io/en/latest/advanced/#including-snippets-in-pages

**Comment by SadParad1se** [comment]
Hi, I have a similar problem. I have a YAML file (Jinja template) in the `docs` directory. However, I'm unable to render its variables. 

The file (`docker-compose.yml`) contains a configuration that the user can download directly. For example:
```yaml
foo:
  bar: {{ predefined_value }}
```

(The variable `predefined_value` is defined in an external file.)

Project structure:
.
├── docs
│   ├── getting-started
│   │   ├── docker-compose.yml
│   │   └── quick-start.md
│   ├── index.md
└── mkdocs.yml

Is there a way to render variables on non-markdown pages?

**Comment by fralau** [comment]
So wou wish to render an external page, that will not be displayed? Where do you want the result to be stored?

**Comment by fralau** [comment]
@spettinichi  In the latest version of the doc, including external files has been included under [Advance use](https://mkdocs-macros-plugin.readthedocs.io/en/latest/advanced/#including-external-files-in-pages) (there is a problem with the display of the code examples, because the readthedocs environment seems to "eat" the include directives).

@SadParad1se I agree that mkdocs-macros might not be the ideal tool for that, and you might need an external jinja2 engine (or, at worst, write your own; it's not very difficult).

**Comment by SadParad1se** [comment]
Okay. Thanks to both of you.
