### ISSUE TITLE
Allow opt-in of page rendering, instead of opt-out

### ISSUE THREAD

**Issue by fralau** [fralau/mkdocs_macros_plugin#162]
Large projects sometimes have too many pages, to allow them to change them all. 

In those cases, it would be easier to render only the pages that require it.

See PR (not used): https://github.com/fralau/mkdocs_macros_plugin/pull/159#issue-1664812954

**Comment by fralau** [comment]
### Opt-in

The solution will be to use in the header:

```yaml
---
# YAML header
render_macros: true
---
```

Opt-in is set in the config file:
```yaml
plugins:
  - search
  - macros:
      render_by_default: false
```

### Opt-out

This is the default case. If you want to be explicit, you can set the parameter `render_by_default` to true, in the config file.

In the page, use the following directive:

```yaml
---
# YAML header
render_macros: false
---
```

This one will be maintained for compatibility (deprecated):

```yaml
---
# YAML header
ignore_macros: true
---
```

**Comment by attie** [comment]
Would you like me to rework the PR?

**Comment by fralau** [comment]
Thanks! Actually I just implemented and tested it as I went. I should be able to push it today.

**Comment by fralau** [comment]
@attie @hexus This is pushed, if you wish you can started to test if that works for you?

**Comment by attie** [comment]
@fralau Perfect, thanks very much! Any idea when you plan to push to PyPi? (no hurry, I'd just like to know so I can drop the git reference)

**Comment by hexus** [comment]
Works well for me too, @fralau. Cheers!

I wasn't particularly in need of this global override for my current project, just offering my two cents on #159. ☺️

Nice to have though, and I think it'll be useful for future projects.

**Comment by fralau** [comment]
Thanks to both of you, for your input and for testing! 

That's part of the 1.0.0 project. The more people test it, the better it is!
