### ISSUE TITLE
Global append & prepend configuration (header and footer)

### ISSUE THREAD

**Issue by hexus** [fralau/mkdocs_macros_plugin#164]
Hello there! This is a small suggestion that I mentioned as an alternative solution for issue #162.

A convenient feature would be MkDocs-configured auto append or auto prepend files for each page, much like [**`pymdownx.snippets`'s `auto_append` configuration**](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#auto-append-snippets).

Example:

```yml
plugins:
  - macros:
      auto_prepend:
        - header.md
      auto_append:
        - footer.md
      include_dir: includes
      include_yaml:
        - includes/glossary.yml
```

A configuration like this would prepend `includes/header.md`, and append `includes/footer.md`, to all rendered pages. Of course, it would be possible to add more paths to the lists to prepend/append more files.

I think something like this would be helpful for a few reasons:

1. Macro-interpreted global includes ala #158
   but without any custom Python 🐍 
2. Easier to keep page Markdown content lean for the common use cases: `glossary.md`, `links.md`, etc 📚 
3. Less reason to use `pymdownx.snippets`! ✂️ 

Cheers!

**Comment by fralau** [comment]
Thanks!  It's good to have a comparison, too.

Essentially, the case for this feature would be that it would be much easier to implement a common header/footer in this way, than to write a macro? (There needs to be a strong case, because general policy is to keep the code lean, i.e. not to implement features that could be easily implemented with a macro or pluglet)

For simplicity, I would call the two parameters `header` and `footer`.

What would be the case for more than one footer or header?

Note that this would be with the the general frame of the page, which is implemented through the mkdocs theme. [Headers and footers can be defined as templates](https://www.mkdocs.org/user-guide/customizing-your-theme/) (see also for the [material theme](https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/). Probably, most users won't want to touch that, but it's worth keeping in mind.

**Comment by hexus** [comment]
Well, I suppose you could do so with a macro? But then you'd need to use the macro on every page. Otherwise, how would one apply this to every page _with_ macro interpretation (Jinja rendering)?

At that point it'd make more sense, to me at least, to use [template inheritance](https://jinja.palletsprojects.com/en/3.1.x/templates/#template-inheritance) and blocks, etc, which I'm actually very much considering at the moment! But then this becomes less readable and straightforward when viewing content outside of the generated website, and in something like GitHub/GitLab instead. This is what I meant by keeping Markdown content lean, I suppose.

And indeed, I've considered modifying the theme (I use Material for MkDocs, it's awesome), but I also like the idea of keeping the content itself (the Markdown) as portable and as uniform as possible. Separation of concerns from MkDocs itself, which I think of as the "container" of the content.

The case for more than one header and footer in my mind is simply separation of concerns, but indeed it wouldn't be a necessity IMO, just a nicety. As an example, I have a `links.md` for external links and a `glossary.md` for glossary entries, both of which would be included as footers.  Of course, they could easily be merged into a `footer.md`, but the separation is helpful in my case. Equally, if a single footer was templated - which it would be thanks to #158 - I could just use separate includes in a single `footer.md`:

```md
{% include 'links.md' %}

{% include 'glossary.md' %}
```

So being able to configure multiple header/footer files isn't really much of an issue. I guess I'm just a bit of a purist, wanting to avoid the Python I now have that does the same thing:

```py
def define_env(env):
    "mkdocs-macros-plugin module: Adds a macro-interpreted footer to all pages"

# https://github.com/fralau/mkdocs_macros_plugin/issues/158
def on_pre_page_macros(env):
    env.markdown += "\n\n{% include('links.md') %}\n\n{% include('glossary.md') %}"
```

The purist in me likes the idea of moving this to config instead:

```yml
plugins:
  - macros:
      prepend: header.md
      append:
        - links.md
        - glossary.md
```

While I do consider my suggestion here a "convenience" feature, the main motivation is that a header/footer - in my use case, at least - would provide primarily supplementary content, and it's nice to be able to include that on all pages easily, as part of the same configuration includes `.yml` (`include_yaml`). Perhaps it'd make more sense if I called them "global includes". 😁

**Comment by fralau** [comment]
Thanks!  Yes I can see the semantic confusion between a _macro_ in the sense of mkdocs-macro (a python function made available to the Jinja2 engine) and a _macro_ in the sense of Jinja2 (written in Jinja2).

I appreciate your purist approach to the issue of headers and footers (which is my concern with this plugin). I agree with the idea of "container/content" and generally keeping separation of concerns.

A little practical problem is that in your example:

```yaml
plugins:
  - macros:
      header: header.md
      footer:
        - links.md
        - glossary.md
  ```

The header is a string, and the footer is a list isn't it? The mkdocs API is not that discerning; and if I declare a "list", it will want a list, which has a rather clumsy syntax (`header=[header.md]`). Will that not complicate the life of most users and generate question after question? This is why I would keep it simple for the majority of users: and let the minority the burden to use a Jinja2 include (that would be a consideration of "general interest" versus "particular interest").


My second question is more general (related to daily life, not directly to mkdocs-macros): what would you put in a header or footer? The example I saw in `auto_append` is a glossary (which is OK, but not a case I have met). What would you use it for? Could other websites have the same need? What would they put into a header or footer?

**Comment by hexus** [comment]
> I appreciate your purist approach to the issue of headers and footers (which is my concern with this plugin). I agree with the idea of "container/content" and generally keeping separation of concerns.

Wonderful! 🙏 

> The mkdocs API is probably not that discerning; and if I declare a "list", I guess it will want a list, which has a rather clumsy syntax (`header: [header.md]`).

Haha, I didn't realise MkDocs was that inflexible! I assume union type would be possible, i.e. `string|list`, that's why I wrote an example like that. So that `header: header.md` is equivalent to `header: [header.md]`. Still, easily solved by making both lists, or both strings, depending on implementation choice.

If you wanted to support multiple files for each:

```yml
plugins:
  - macros:
      headers:
        - header.md
      footers:
        - links.md
        - glossary.md
```

Or:

```yml
plugins:
  - macros:
      headers: [header.md]
      footers: [links.md, glossary.md]
```

Either list syntax is up to the user. I prefer the nested syntax to the inline syntax, personally.

And if you don't want to support multiple files, then just make them strings, sure:

```yml
plugins:
  - macros:
      header: header.md
      footer: footer.md
```

## Header example

As for use cases for a header, in pure Markdown I can't think of much. But with Jinja, and the mighty potential of the arbitrary YAML-includes from this plugin, aren't the possibilities endless?

Something I just thought of would be page breadcrumbs. This is a [sponsors feature for Material for MkDocs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-path), but could easily be implemented with a header and some Jinja that processes the page's file path.

In fact, I liked the idea so much that I just whipped up a quick `header.md` to try it out, using [the plugin's variable reference](https://mkdocs-macros-plugin.readthedocs.io/en/latest/pages/#batteries-included-default-objects) and [Jinja 2's recursive loop syntax](https://jinja.palletsprojects.com/en/3.1.x/templates/#for):

```jinja
{{ config.site_name }} > 
{%- for item in [page] recursive -%}
  {%- if item.parent -%}
    {{ loop([item.parent]) }} >
  {%- endif %}
  {%- if item.url %}
    [{{ item.title }}]({{ item.url }})
  {% else %}
    {{ item.title }}
  {%- endif %}
{%- endfor %}
```

Try it out! It's just a quick test, and it doesn't create links for section-pages yet, but I doubt that'd be too difficult.

## Footer examples

As for my footer, I include a `glossary.yml` list to a `glossary` variable which I can use to generate a glossary page:

```jinja
# Glossary

<!-- `markdown` attributes are needed for MkDocs to find the headings for the ToC -->

<dl markdown>
{% for term, description in glossary.items() %}
<dt markdown>
<h2>{{ term }}</h2>
</dt>
<dd>{{ description }}</dd>
{% endfor %}
</dl>

```

And then use the same data for a `glossary.md` footer, utilising [Material's glossary feature](https://squidfunk.github.io/mkdocs-material/reference/tooltips/?h=glossary#adding-a-glossary).

```jinja
{% for term, description in glossary.items() %}
*[{{ term }}]: {{ description }}
{% endfor %}
```

And a separate `links.md` footer file for external links that are used across the whole site:

```md
[Link 1](https://example.com/1)
[Link 2](https://example.com/2)
[Link 3](https://example.com/3)
```

---

All of the above is all based on my usages in a personal project at the moment, but I think of the possibilities are endless. Already thinking about how I'd this kind of setup for @Claromentis documentation sites!

Honestly though, no worries if you don't feel this feature is fit for the plugin config. As I said, just a suggestion. I'm kinda done justifying it now. 🙃 Main thing is, I can always use a simple event hook:

```py
def on_pre_page_macros(env):
    env.markdown = "{% include('header.md') %}\n\n" + env.markdown
    env.markdown += "\n\n{% include('links.md') %}\n\n{% include('glossary.md') %}"
```

**Comment by fralau** [comment]
Thanks, I'd say we have a very good case here! 

It's not urgent (since it can be done as you described), but we can keep it there, in case this comes up again!

**Comment by fralau** [comment]
I am closing this issue, but I invented the "keep in mind" label for it. 👍

**Comment by hexus** [comment]
Cheers, thanks for taking it into consideration ✨
