### ISSUE TITLE
Variable not support Chinese characters

### ISSUE THREAD

**Issue by icebilly** [fralau/mkdocs_macros_plugin#166]
Seems to be a charset issue.
The content in red is from a variable, it's not decode correctly.
![image](https://github.com/fralau/mkdocs_macros_plugin/assets/21252620/08413a5b-9f0c-4816-8a09-4cc33b370f6a)

**Comment by fralau** [comment]
There is no specific handling of characters in the code mkdocs-macros. Could you describe the problem more in detail?

**Comment by icebilly** [comment]
> There is no specific handling of characters in the code mkdocs-macros. Could you describe the problem more in detail?

It's a codec issue, if I save the yml file with gbk codec, the chinese characters can be rendered correctly.
Is there any possible to add a codec option in the plugin to let the user choose which codec they want to decode.

**Comment by fralau** [comment]
I am not familiar with those issues. There is no invocation of codecs in MkDocs macros. Where should that ideally take place?

**Comment by yanedie** [comment]
> I am not familiar with those issues. There is no invocation of codecs in MkDocs macros. Where should that ideally take place?

I know the solution. Just open the md file in VS Code and choose the encoding at the bottom bar, generally it's UTF-8, click it and choose repoening with encoding, choose gbk. By the way, I open a discussion in github discussion, could you help me? Thx!
