### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources' on python 3.12

### ISSUE THREAD

**Issue by dunossauro** [fralau/mkdocs_macros_plugin#169]
On python 3.12 beta we can't install mkdocs-macro, pkg_resources [does not exist](https://docs.python.org/3.13/whatsnew/3.12.html#removed)

```
 File "/.../.venv/lib/python3.12/site-packages/mkdocs_macros/__init__.py", line 7, in <module>
    from .context import fix_url, is_relative as is_relative_url
  File "/.../.venv/lib/python3.12/site-packages/mkdocs_macros/context.py", line 19, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

Related to #157

**Comment by fralau** [comment]
This is apparently not an mkdocs-macros issue, but due to a broken setuptools install:
https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources

Let me know if fixing setuptools fixed the issue for you?

**Comment by fralau** [comment]
Is this problem still open?

**Comment by calebAtIspot** [comment]
@fralau this is a mkdocs-macros issue. pkg_resources has been deprecated and should no longer be used.

https://setuptools.pypa.io/en/latest/pkg_resources.html

> Use of pkg_resources is deprecated in favor of [importlib.resources](https://docs.python.org/3.11/library/importlib.resources.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3.11/library/importlib.metadata.html#module-importlib.metadata) and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Some useful APIs are also provided by [packaging](https://pypi.org/project/packaging) (e.g. requirements and version parsing). Users should refrain from new usage of pkg_resources and should work to port to importlib-based solutions.

Relevant: https://github.com/mu-editor/mu/issues/2485
