### ISSUE TITLE
mkdocs build error: No module named 'packaging'

### ISSUE THREAD

**Issue by jasminnancy** [fralau/mkdocs_macros_plugin#179]
I kept getting this error:
```js
File "/usr/local/lib/python3.9/site-packages/mkdocs_macros/util.py", line 10, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
```

My mkdocs kept failing after the addition of this line:
https://github.com/fralau/mkdocs_macros_plugin/blob/9dba19e3ec0dfce7761eee32dfda4dca6cd312af/mkdocs_macros/util.py#L10

The resolution was just to add `packaging` to my requirements.txt file.
An easy fix, but annoying nonetheless.

**Comment by fralau** [comment]
Thanks for the heads up.

Updated on git. It will be on pypi with next tagged version.
