### ISSUE TITLE
Setting for include root directory

### ISSUE THREAD

**Issue by majkinetor** [fralau/mkdocs_macros_plugin#19]
Currently:

> The root directory for your included files is in `docs_dir`

How about making this plugin configuration that defaults to `docs_dir` if not set ?

```yaml
- macros:
      root_dir:  inc       <== relative to the mkdocs.yml location
```

Currently I need to put this in the docs folder with other files, but then those files get rendered also which is wrong as they are partials. Then I need exlusion plugin etc... This folder should be outside of docs to avoid that hessle and currently this is not possible to set.

**Comment by fralau** [comment]
Good point, worth looking at.

**Comment by fralau** [comment]
As a workaround, have you tried e.g. `{% include '../inc/snippet.md' %}` ?

**Comment by fralau** [comment]
Using a different directory than docs for the includes makes sense to me. I am considering an `include` directory besides `docs`.

However, changing the default behavior might impact for existing users. Would @mlenkeit @Justin-W  @janoszen or @ryandaugherty like to express views about this?

**Comment by majkinetor** [comment]
> As a workaround, have you tried e.g. {% include '../inc/snippet.md' %}

Yes, and it works as far as I remember but then you have to put `../inc/` everywhere so its becomeing noisy.

**Comment by fralau** [comment]
Agreed, this is noisy.

**Comment by majkinetor** [comment]
Not only noisy but errorprone. Next person will put something like `include` instead of `inc` and so on.

**Comment by fralau** [comment]
Understood.

This is implemented with #41a89c1 (4.1). The parameter is called `include_dir`, e.g.:
```
plugins:
  - search
  - macros:
      include_dir: include
```
The default stays as before (uses the `docs` directory).

Could you let me know if this works for you?

**Comment by fralau** [comment]
Note that I have pushed a new version (285294f, 0.4.2). 

During development (`mkdocs serve`), the new 'include' directory is now being "watched": and a modification of one of the partial pages will reload the pages.

**Comment by majkinetor** [comment]
Everything works great. Thx.
