### ISSUE TITLE
Plugin does not work unless an extra variable is specified

### ISSUE THREAD

**Issue by synapse211** [fralau/mkdocs_macros_plugin#21]
Plugin does not work unless you add a variable to mkdocs.yml under "extra".

This is not mentioned in the documentation at all.

**Comment by fralau** [comment]
That would be a bug. Could you give me more specifics about it? (code, logs, etc.)

**Comment by synapse211** [comment]
I threw together a quick demo of the bug:

https://github.com/synapse211/mkdocs-bug

If you comment out the extra section from mkdocs.yml and restart you can see the bad behaviour.

**Comment by fralau** [comment]
Thanks, I tried to replicate this bug by removing the `extra` part in the yaml  config file, but everything worked OK. I have been working on a new version that I will push to the repo. Perhaps you will want to try it as soon as it is pushed?

**Comment by synapse211** [comment]
I just tried to comment it out, I didn't actually remove it, but it really should not matter.

Sure, I can try the new version. When will that happen?

**Comment by fralau** [comment]
We now have a v.0.4.0 on the repository. You are welcome to test it.

**Comment by synapse211** [comment]
This seems to have fixed it.

**Comment by fralau** [comment]
Thanks a lot for your feedback! I close the issue.
