### ISSUE TITLE
Any issues with with version 0.4.4?

### ISSUE THREAD

**Issue by fralau** [fralau/mkdocs_macros_plugin#27]
Before I push this version to pypi, a broad question: are you experimenting any issues with this version? Any feedback?

**Comment by mallowigi** [comment]
How do i install this version ?

**Comment by fralau** [comment]
Good point!

1. clone the repo
2. `python setup.py install`

**Comment by mallowigi** [comment]
When do you think you’ll be pushing it? I want to try it asap

**Comment by fralau** [comment]
0.4.4 has been released on pypi.
