### ISSUE TITLE
Include parts of file

### ISSUE THREAD

**Issue by majkinetor** [fralau/mkdocs_macros_plugin#29]
I have some big files I need to reference different portions (line1 to line2) on specific places. Is this possible  some way ?

For example: `{% include('setup.py',13,15) %}`

This would look the same as here on Github: `/setup.py#L13-L15`

https://github.com/fralau/mkdocs_macros_plugin/blob/d2739362d22a8c37668f8f0d9d4f7e081708f407/setup.py#L13-L15

**Comment by fralau** [comment]
You could indeed. 

The standard way to do that, would be to write it in your own module `main.py`:

https://mkdocs-macros-plugin.readthedocs.io/en/latest/python/

Essentially you would write that function with the `@env.macro` decorator and it would automagically become available as a macro. Let me know if that works for you?

**Comment by majkinetor** [comment]
OK, I will try and let you know how it went :)

**Comment by fralau** [comment]
How did it go?

**Comment by majkinetor** [comment]
Well, I got this error with latest pypi version 0.4.4 with python 3.6:

```
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'text'
```

My workflow is such that testing a new pypi version takes zero time and I have to do lots of manual work to test it otherwise. Could you relase 0.4.6 ?

**Comment by majkinetor** [comment]
It didn't go yet :) Will try to find some time for it soon. I will close this for now, and will let you know when I do it.

**Comment by fralau** [comment]
I kept your question in mind, so I solved it (it works). I thought it would be a good case for the documentation, so I put it in the [Tips and Tricks](
https://mkdocs-macros-plugin.readthedocs.io/en/latest/tips/#i-would-like-to-include-a-text-file-from-line-a-to-line-b).

Le me know what you think?

**Comment by majkinetor** [comment]
Awesome. I like it.
Thanks a lot.
