### ISSUE TITLE
Plugin fails to load if Git is not in PATH

### ISSUE THREAD

**Issue by mjameson-se** [fralau/mkdocs_macros_plugin#30]
This may be limited to Windows, I don't have a linux setup to test with at the moment. All I was getting was this weird error message "[WinError 2] The system cannot find the file specified". Hacked up the plugin source to add some except blocks to try to trace it back to the root cause and:
```
Traceback (most recent call last):
  File "c:\users\sesa249423\appdata\local\programs\python\python38\lib\site-packages\macros\plugin.py", line 313, in on_config
    define_env(self)
  File "c:\users\sesa249423\appdata\local\programs\python\python38\lib\site-packages\macros\context.py", line 239, in define_env
    env.variables['git'] = get_git_info()
  File "c:\users\sesa249423\appdata\local\programs\python\python38\lib\site-packages\macros\context.py", line 147, in get_git_info
    r[var] = subprocess.check_output(command,
...
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
Hacking up the source more, I was able to simple change the `except` clause to omit the exception type so it catches any exceptions, now it works fine.

**Comment by anotherbit** [comment]
Same issue as @mjameson-se if I don't have git on my path (I am on Windows).  Looks like we need to catch the FileNoteFoundError in this case.

**Comment by fralau** [comment]
Thanks for the heads up.

**Comment by fralau** [comment]
OK it's fixed in 2bd7950  (0.4.7).

Could you please confirm that it works on your side?

**Comment by mjameson-se** [comment]
Looks good. Thanks!

**Comment by anotherbit** [comment]
Confirmed working, thanks for the quick fix!
