### ISSUE TITLE
TypeError: on_serve() got an unexpected keyword argument 'builder'

### ISSUE THREAD

**Issue by alexey74** [fralau/mkdocs_macros_plugin#33]
mkdocs, version 1.1.1

happens when I run `mkdocs serve`

**Comment by fralau** [comment]
For the record, and to make sure that my understanding is correct: with the release of [mkdocx 1.1.1](https://github.com/mkdocs/mkdocs/releases/tag/1.1.1) (published 4 days ago) a new argument is being passed to the `on_serve()`method, which causes it to break?

**Comment by fralau** [comment]
No answer, unfortunately. But it checks out.
