### ISSUE TITLE
Regression: custom 'module_name' doesn't work with '__init__.py' - style modules anymore

### ISSUE THREAD

**Issue by makkus** [fralau/mkdocs_macros_plugin#43]
Just upgraded from 0.4.9 and getting the error message below. It happens when the Python module that the ``module_name`` configuration value points to is an ``__init__.py`` file.

I think it has to do with the recent refactoring of the module import that happened here (but haven't had time to investigate more yet): https://github.com/fralau/mkdocs_macros_plugin/commit/e419062e2ec2f7bf2c1e332a6ee90e5be8d559aa#diff-15d04a928c1fac5996433591e06a4569

Relevant config:
```
plugins:
- search
- macros:
   module_name: ci
```

Error stack:

```
❯ mkdocs build --site-dir public
[macros] Macros arguments: {'module_name': 'ci', 'include_dir': '', 'include_yaml': [], 'j2_block_start_string': '', 'j2_block_end_string': '', 'j2_variable_start_string': '', 'j2_variable_end_string': ''}
Traceback (most recent call last):
  File "/tmp/tingex/.direnv/python-3.8.5/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/tmp/tingex/.direnv/python-3.8.5/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/tingex/.direnv/python-3.8.5/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/tmp/tingex/.direnv/python-3.8.5/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/tingex/.direnv/python-3.8.5/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/tingex/.direnv/python-3.8.5/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/tmp/tingex/.direnv/python-3.8.5/lib/python3.8/site-packages/mkdocs/__main__.py", line 152, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/tmp/tingex/.direnv/python-3.8.5/lib/python3.8/site-packages/mkdocs/commands/build.py", line 236, in build
    config = config['plugins'].run_event('config', config)
  File "/tmp/tingex/.direnv/python-3.8.5/lib/python3.8/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/tmp/tingex/.direnv/python-3.8.5/lib/python3.8/site-packages/macros/plugin.py", line 314, in on_config
    self._load_module()
  File "/tmp/tingex/.direnv/python-3.8.5/lib/python3.8/site-packages/macros/plugin.py", line 242, in _load_module
    raise ImportError("Macro plugin could not find custom '%s' "
ImportError: Macro plugin could not find custom 'ci' module in '/tmp/tingex'.
```

**Comment by fralau** [comment]
@makkus Thanks. Perhaps I have a clue: `--site-dir public`.

The location of the module is assumed to be in the same place as the config file (`mkdocs.yaml`).  Is that the case? 

In any case, I find it strange that it expects the module in `/tmp/tingex` 🤔 . Is that the directory from where you called `mkdocs build` ?

**Comment by makkus** [comment]
> @makkus Thanks. Perhaps I have a clue: `--site-dir public`.
> 
> The location of the module is assumed to be in the same place as the config file (`mkdocs.yaml`). Is that the case?

Sorta, the 'root' of the module is the directory where 'mkdocs.yaml' is located, but I guess I expected that to not matter. As long as the module is available in the current (virtual)env, it should be picked up, no?

If I run a Python REPL and do 'import ci' the module (aka the '__init__.py' file) is picked up fine. So maybe it would make sense to use the 'normal' Python way of importing the module, then use the '__file__' attribute to determine the path to the file, and not try to construct the path manually? I have to admit I don't fully understand what's involved though, so maybe what I just said doesn't make any sense.

> In any case, I find it strange that it expects the module in /tmp/tingex thinking . Is that the directory from where you called mkdocs build ?

Sorry, that was just for testing. I checked out a 'clean' repo into /tmp so I could investigate why it stopped working all of a sudden. Turned out it was the version of mkdocs_macros_plugin'...

**Comment by fralau** [comment]
@makkus Got it. Even better if it's in `/tmp`. Could you outline the tree of your project, so that I can replicate it?

**Comment by makkus** [comment]
Sure. I created a stripped down repo from my usual Python template: https://github.com/makkus/mkdocs_macros_regression

I have the actual project code in a different directory (src/*) to all the ci-related stuff (like the macros config/helper methods -- under ``ci/docs`` in this case). That shouldn't matter though, as all that matters is that Python can find it in the (virtual)env. This specific layout may look a bit extra weird, but the underlying problem would still apply to simpler setups.

**Comment by fralau** [comment]
@makkus It was a bug (the case where the plugin was a directory instead of a file did not work). This should be fixed with the last push (3ffd99e, 0.4.16).
Could you give it a try?

**Comment by makkus** [comment]
Yup, all good. Thanks for the super-quick fix, much appreciated!

**Comment by makkus** [comment]
Ok, this stopped working again after 0.4.16. Until 0.4.16 it worked. The minimal template I provided above can still be used to reproduce the issue. If I am not mistaken then the core problem is described in: https://github.com/fralau/mkdocs_macros_plugin/issues/49 -- so I will continue the discussion over there.

**Comment by fralau** [comment]
@makkus Is it a local or pre-installed module?

**Comment by makkus** [comment]
Sorry, I'm getting a bit confused now :-) Should we close this and continue the conversation over at the other issue? The module is in the Python environment, I'm not sure why it would matter? But in this case it would be a module(-file) in the local project.

**Comment by fralau** [comment]
@makkus Fine for me.
