### ISSUE TITLE
Unable to process markdown files that contain default Jinja template markers

### ISSUE THREAD

**Issue by makkus** [fralau/mkdocs_macros_plugin#5]
If this plugin tries to process a markdown template that contains default Jinja template markers, this will fail. For example, imagine a markdown file trying to explain some Ansible features. Might look something like:

```
The Ansible file task  works like this:

- task: "create a directory
  file:
    path: "{{ folder_path }}"
    state: directory
    recurse: true
```

This won't work, as the 'folder_path' variable won't be in ``extra``. And it should not render that particular string in the first place.

Does that make sense?

**Comment by fralau** [comment]
To be sure we are on the same page, you intention is that `{{ folder_path }}` should *not* be interpreted by the Jinja2 engine? 

Conceptually, is it because it is a 'quote'; or because it is going to be processed later?

**Comment by makkus** [comment]
You are overthinking it :-)
Basically, all I want is for strings that include Jinja markers to appear in the final html page. To be able to document stuff that uses Jinja markers. For those cases it'd be good to be able to specify different 'real' markers, that will be used by this plugin. Does that make sense?

I decided to write my own mkdocs plugin for what I need now though, as that gives me more flexibility, (plus Python 2.7 support) so don't worry if you don't see a point in including this as a feature.

**Comment by fralau** [comment]
Actually I am genuinely interested by your contribution :-) 

Bear with me: the reason why I am asking, is that if you were only trying to prevent interpretation of that specific item by *this* Jinja2 template engine, there was a much straightforward solution: [escaping](http://jinja.pocoo.org/docs/2.10/templates/#escaping).

```
{% raw %}
- task: "create a directory
  file:
    path: "{{ folder_path }}"
    state: directory
    recurse: true
{% endraw %}
```

Is that not something that would have solved your issue? Or was there something else?

By contrast, your (elegant!) patch would make sense in the case I mentioned before, i.e. when there is a conflict between two different successive applications of template engines (a situation that is not so uncommon, BTW, and I have already met). 

Let me know.

**Comment by makkus** [comment]
Hahahah. Totally forgot about {% raw %}...  Speaking of overthinking... :-)

**Comment by fralau** [comment]
We reopen this issue in view of the dicussion in #4

**Comment by fralau** [comment]
Solved with commit ac912e0

**Comment by fralau** [comment]
@DominikaK, let me know if it worked for you?

**Comment by DominikaK** [comment]
Thank you, the plugin is working as expected with our setup now. Looking forward to using it!

**Comment by fralau** [comment]
You're welcome!
