### ISSUE TITLE
Don't require mkdocs-material in setup.py?

### ISSUE THREAD

**Issue by jimporter** [fralau/mkdocs_macros_plugin#50]
This is a pretty minor issue, but setup.py requires `mkdocs>=0.17` and `mkdocs-material`. The latter requires `mkdocs>=1.1`, so if you try to install a pre-1.1 version of `mkdocs` along with `mkdocs-macros-plugin`, you'll get a non-fatal error from `pip` that `mkdocs` is incompatible:

```
ERROR: mkdocs-material 6.1.6 has requirement mkdocs>=1.1, but you'll have mkdocs 1.0.4 which is incompatible.
```

It looks like `mkdocs-material` is only required in this package for the tests, so it doesn't actually need to be installed for all users. I think the Pythonic way of listing dev/test dependencies is with a `requirements.txt` file; an alternative would be `extra_requires` in setup.py:

```python
...
extras_require={
    'test': ['mkdocs-material'],
},
...
```

Then people who want to test this package could call `pip install 'mkdocs-macros-plugin[test]'`.

Assuming this makes sense, I'm happy to make a PR for this or for anyone else to do so. I'm not picky. :)

**Comment by fralau** [comment]
@jimporter Thanks a lot. Indeed, that was on the back of my mind, and your solution sounds excellent. 

I will be happy if you make a PR for that ! 🙂

**Comment by fralau** [comment]
Installation procedure must be updated for include `test` part.

**Comment by fralau** [comment]
@jimporter Thanks a lot !
