### ISSUE TITLE
Get url parameters

### ISSUE THREAD

**Issue by Greenfoot5** [fralau/mkdocs_macros_plugin#55]
Is it possible to get any url parameters that might be entered? So, if my url is `https://example.com/wiki_page/?code=5`, can I get the `5` from the url? And url variables I've tried to find can get all the url up to the `?`.

**Comment by fralau** [comment]
This question is more related to MkDocs, but  I'll try to give you a few pointers anyway.

Remember that MkDocs produces _static_ HTML pages; there is no server-side code (PHP or node.js). So at that point, the only "dynamic" thing that is left, is Javascript running on the client (browser). You could pull that `code=5` value [following this advice advice on StackOverflow](https://stackoverflow.com/questions/6944744/javascript-get-portion-of-url-path) (perhaps something like `windows.location.search` ?).

**Nothing prevents you from throwing some [HTML(and thus even embedded JavaScript)](https://daringfireball.net/projects/markdown/syntax#html) in one of your markdown pages**. Then, if you wish to package that well, you could write a macro to produce that HTML/javascript code. 

But the first step, I believe, would be to write the JavaScript code that would do the white magic that you wish (btw, what you wish to accomplish with that `code=5` value?).

**Comment by Greenfoot5** [comment]
I'm trying to create a leaderboard, and I have all the data, except for the user's name. That I need to interact with an api, in which I need to use OAuth to obtain the data. In which case, my code would be the token used to interact with the api, and get the user's names.

I was trying to avoid the Javascript part, as I wasn't sure if I could link it with the Python, or if I'd have to learn how to interact with the database in Javascript.

I'm aware that mkdocs isn't designed for this, but I'm too lazy to transfer everything to a new wiki style.

**Comment by fralau** [comment]
Yeah... Javascript might not be a good idea for that. 

I also relate to the "lazy" instinct (as long as it doesn't become a rabbit hole: at which point the "lazy" instinct should kick in again, and you might want to do the _standard_ thing).  

So you may try to think a little out of the box ? E.g. you could use a form processor written in [php](https://www.php.net/manual/en/intro-whatis.php). Note that this page must probably have the `.php` extension. This may be tricky with MkDocs (which produces only `.html` files, but [you _can_ manage the addition of that file to the "package" with mkdocs_macros](https://mkdocs-macros-plugin.readthedocs.io/en/latest/advanced/#adding-post-build-files-to-the-html-website)) ?

**Comment by Greenfoot5** [comment]
The API allows a different way to interact with it so I have managed to display the leaderboard. Thanks for the help though!
