### ISSUE TITLE
Help with git revision date macro

### ISSUE THREAD

**Issue by majkinetor** [fralau/mkdocs_macros_plugin#6]
How could I create macro `{{git_revision}}` that would get replaced by the git revision of **that file which it is part of**.

I wanted to do it as a part of the module but not sure how to get a path to the markdown file.

**Comment by fralau** [comment]
To me, it seems a more general issue, i.e. a Python issue.
Could the following help?
https://stackoverflow.com/questions/14989858/get-the-current-git-hash-in-a-python-script

**Comment by fralau** [comment]
Just curious: which command would you use?

Something like:
```
git ls-files -s my_file.md
```

**Comment by majkinetor** [comment]
After some thought I think this option would require complete list of files with current date/hash prior to build as calling git executable once per each file is very slow and you don't need to have git repository available in full (i.e monorepo with docker build).

Then `{{git_revision}}` would use this file to get the info.

**Comment by fralau** [comment]
For info, I did such a hack on a project, to dump the project name + git tag:

```
# Update the info file
FILENAME='gitinfo.txt'
echo "#THIS FILE IS AUTOMAGICALLY CREATED (by $0) DO NOT MODIFY IT" >$FILENAME
basename "`git rev-parse --show-toplevel`" >> $FILENAME
git describe --tags >> $FILENAME
```

Then, in `main.py` you would have to write a function without arguments that reads this file, which should be pretty straightforward:

```
def define_env(env):
    """
    This is the hook for the functions (new form)
    """
    @env.macro
    def git_revision():
        "Read the revision number from the file"
       ....
```

**Comment by majkinetor** [comment]
How do I know for which file/pageI am getting revision ?

**Comment by fralau** [comment]
It would depend on how you want to hardcode the filename in your procedure or not. Since you wished to have a `{{ git-revision }} ` field, that would look like the best solution.

If you really want to make the filename configurable, you could put it in the yaml file, typically in the `extra` namespace (so that you can easily access it from the module).

**Comment by majkinetor** [comment]
I am talking about a page file path.

So lets say I put this in a file `revisions.txt` which contains lines in a form `page_path last-change-date`.

I [generate](https://github.com/majkinetor/mm-docs-template/blob/56309e12683305b248e59513f91ae61262c0efe9/docs.build.ps1#L119-L140) `revision.txt` before build. 

Then I have a function:

**Comment by fralau** [comment]
I would do it this way:

```
    FILENAME = 'path/to/revisions.txt'
    def git_revision():
        "Read the revision number...."
    ....
```
or, if you have defined a variable in the `mkdocs.yml`file:
```
extra:
   - revisions = 'path/to/revisions.txt
```

Then, in your module:
```
    FILENAME = env.variables('revision_file')
```

**Comment by fralau** [comment]
I see your point. Currently, you should either use an absolute path, or [a path relative to your source code](https://stackoverflow.com/questions/7162366/get-location-of-the-py-source-file) (i.e. the module).

```
import os 
dir_path = os.path.dirname(os.path.realpath(__file__))
```

**Comment by majkinetor** [comment]
That will return path fo `main.py`, not the path to the page.

**Comment by fralau** [comment]
That's right. Then you can work out your path.

**Comment by fralau** [comment]
Actually, you can get your version on the fly (for the website/project repo):

```
import subprocess
def define_env(env):
    """
    This is the hook for the functions (new form)
    """

    GIT_VERSION = ['git', 'describe', '--tags']
    env.variables['git_version'] = subprocess.check_output(GIT_VERSION, 
                                            text=True).strip()

```

**Comment by majkinetor** [comment]
> That's of course providing your project is under git version control, you have already defined a git tag.

That is the problem - it is in git but in monorepo. That means .git folder is generally not available during build since its upper in the hierarchy (and to make it so complicates build).

So, having index file is general solution for any case. Git is specialized solution.

**Comment by fralau** [comment]
I undestand. Since the version control issue itself is not directly connected to mkdocs_macros_plugins, and you should have enough pointers by now, I believe we can close this issue?

**Comment by majkinetor** [comment]
Thanks for the info

**Comment by majkinetor** [comment]
FYI, I finally had time to make this. 

It works this way:

- Prior to build, `revisions.json` is generated using git and copied to docs folder
- I made macro func [changedate ](https://github.com/majkinetor/mm-docs-template/blob/master/source/main.py#L27-L31 )that gets last changed date for current page

This way:
- git doesn't have to be present during mkdocs build time
- it works with monorepo
- other stuff can be quickly added, such as authors, number of words etc.

Demo here, look at the page footer: https://majkinetor.github.io/mm-docs-template/

**Comment by fralau** [comment]
@majkinetor Thanks for the info and 👍  for your solution.

Your project contains some awesome white magic, like:

```yaml
extra:
    url_prefix: !!python/object/apply:os.getenv ["MM_DOCS_URL_PREFIX"]
```

Just curious,

- Why is git not present during build time ? Is it because you are doing some copy of files that excludes the `.git` directory?
- How do you instruct git to create `revisions.json`?

**Comment by majkinetor** [comment]
> our project contains some awesome white magic

All sorts of it really and improving all the time. Its should be zero config to start writing serious docs in it. I use it for all projects and have written thousands of pages in it, book per project.

> Why is git not present during build time ? Is it because you are doing some copy of files that excludes the .git directory?

It was originally that, but I control docker image too and added git in it.

But that didn't work for me - we keep docs project in monorepo  and not single plugin I tried understood that project its deeper in the repository hierarchy and not root.

Also, this way is MUCH MUCH faster - in my docs I have many pages and calling git process for each of them is wasting minutes of time depending on docs size. My function (given bellow) calls git only once before build to generate date index.

> How do you instruct git to create revisions.json?

Look at this PowerShell function:

https://github.com/majkinetor/mm-docs-template/blob/master/docs.build.ps1#L101-L124

Later I only save this info in revision.json and revision.md so you can look at all changes from the [docs itself](https://majkinetor.github.io/mm-docs-template/revision). The plan is to further improve this file: links, diffs, maybe list all revisions of single page etc.

```ps1
Get-GitRevisionDates -Path $DocsDir -Ext '.md' -Skip '*.templates/*', '*/revision.md'
$revisions | ConvertTo-Json | Out-File $DocsDir/revision.json
```

**Comment by fralau** [comment]
@majkinetor Thanks for your update. It's also an opportunity for me to become aware of new things.
