### ISSUE TITLE
 'macros_info' is undefined in overrides/partials/source-date.html

### ISSUE THREAD

**Issue by slookin** [fralau/mkdocs_macros_plugin#60]
macros_info works well on pages, but if I try to add it template - is doesn't work.

mkdocs.yml
```
theme:
  name: 'material'
  custom_dir: overrides

plugins:
  - macros:
      verbose: true
```

overrides/partials/source-date.html
```
<div class="md-source-date">
  {{ macros_info() }}
  <small>
    {% if page.meta.git_revision_date_localized %}
      {{ label }}: {{ page.meta.git_revision_date_localized }} / 
    {% elif page.meta.revision_date %}
      {{ label }}: {{ page.meta.revision_date }}
    {% endif %}
  </small>
</div>

```
logs:

 ```
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /builds/....
DEBUG   -  Reading markdown pages. 
DEBUG   -  Reading: index.md 
DEBUG   -  Reading: summary.md 
DEBUG   -  Reading: test.md 
DEBUG   -  Copying static assets. 
DEBUG   -  Copying media file:
...
DEBUG   -  Building theme template: sitemap.xml 
DEBUG   -  Gzipping template: sitemap.xml 
DEBUG   -  Building theme template: 404.html 
DEBUG   -  Building markdown pages. 
DEBUG   -  Building page index.md 
ERROR   -  Error building page 'index.md': 'macros_info' is undefined 
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/__main__.py", line 152, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 292, in build
    _build_page(file.page, config, files, nav, env, dirty)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 210, in _build_page
    output = template.render(context)
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/material/main.html", line 4, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/lib/python3.8/site-packages/material/base.html", line 150, in top-level template code
    {% block content %}
  File "/usr/local/lib/python3.8/site-packages/material/base.html", line 164, in block "content"
    {% include "partials/source-date.html" %}
  File "/builds/enterprise-api/test/sl-plantuml/overrides/partials/source-date.html", line 11, in top-level template code
    {{ macros_info() }}
jinja2.exceptions.UndefinedError: 'macros_info' is undefined
```

What I'm doing wrong?

**Comment by fralau** [comment]
Wow. I had not thought of putting macros into HTML templates !

The Jinja2 engine of mkdocs-macros (which operates on markdown pages) is completely distinct from the MkDocs usual Jinja2 engine (which operates at a later stage, on the already translated HTML pages). In practice the macros' Jinja2 engine never interferes with the regular one, so most people can safely ignore that curiosity.

In _theory_ it could be possible for the standard template engine to also contain macros... providing I could pass the macros environment (which is essentially a dictionary) to it. I have not begun to explore how much it could make sense, and how the plugin framework would allow me to do that. That's a curious and interesting concept to explore. 🤔 

It could help, if you described what you are attempting to achieve by doing this (your use case) ? And what kind of custom functions or filters would you be looking at ?

**Comment by slookin** [comment]
My "task" was very simple: I want to have **git.tag** value in each page at the bottom.
(it very similar with git_revision_date_localized)

```
<div class="md-source-date">
  {{ macros_info() }}
  <small>
    {% if page.meta.git_revision_date_localized %}
      {{ label }}: {{ page.meta.git_revision_date_localized }} / version: {{ page.meta.git.tag }}
    {% elif page.meta.revision_date %}
      {{ label }}: {{ page.meta.revision_date }}
    {% endif %}
  </small>
</div>

```

For me was big surprise: Why "page.meta.git_revision_date_localized" works and "git.tag" (or "page.meta.git.tag" ) don't?

**Comment by fralau** [comment]
Thanks, and that makes sense. The reason is that `git_revision_date_localized` does not seem to belong to mkdocs-macros... perhaps to another plugin?

Wait a minute: you want to access that info through `page.meta`?

Right now, the variables and macros are _not_ forwarded into `page.meta`.

But you can definitely add values to `page.meta` thanks to the `on_post_page()` hook;
the documentation describes how to do that: https://mkdocs-macros-plugin.readthedocs.io/en/latest/advanced/#directly-influencing-the-markdown-pages-generated

Let me know if that solves your need?

**Comment by fralau** [comment]
Should we systematically push the values to `page.meta`? 🤔 

For example, through an object `page.meta.extra` or `page.meta.macro` ? 

So that it would become `page.meta.macro.git.tag` ?  Why not...

I thought about throwing the values directly into `page.meta` but there would be a risk of accidentally overwriting other values.

This is an open question.

**Comment by slookin** [comment]
>Wait a minute: you want to access that info through page.meta?

I'm also trying just using *git.tag* it also doesn't work. 

`jinja2.exceptions.UndefinedError: 'git' is undefined`

> But you can definitely add values to page.meta thanks to the on_post_page() hook;
> the documentation describes how to do that: https://mkdocs-macros-plugin.readthedocs.io/en/latest/advanced/#directly-> influencing-the-markdown-pages-generated
> Let me know if that solves your need?

Not sure if I understand your recommendation,  are you suggest to create additional python procedure (on_pre_page_macros) in page and fill env.page.meta in this procedure? But what will be name of structure with information about git?

>or example, through an object page.meta.extra or page.meta.macro ?

Doesn't matter for me, even **page.meta.extra.macro.git.tag** is ok.

**Comment by fralau** [comment]
@slookin 

> Not sure if I understand your recommendation, are you suggest to create additional python procedure (on_pre_page_macros) in page and fill env.page.meta in this procedure? But what will be name of structure with information about git?

Yes,, that would be the idea. You define the name you want, e.g. this would call it `page.meta.git`:

```python
def on_post_page_macros(env):
    """
    Actions to be done after macro interpretation,
    just before the markdown is generated
    """
    env.page.meta['git'] = env.variables.git

```

**Comment by slookin** [comment]
Sorry, I check your documentation twice and didn't understand how to extend pages with python procedures.

index.md:
```

{% 
def on_post_page_macros(env):
    """
    Actions to be done after macro interpretation,
    just before the markdown is generated
    """
    env.page.meta['git'] = env.variables.git
%}
# Test Pags


!!! Info
This page just demonstration how Marcos plugin works

```

doesn't work.
```

Macro Rendering Error
TemplateSyntaxError: Encountered unknown tag 'def'.


Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/mkdocs_macros/plugin.py", line 339, in render
    md_template = self.env.from_string(markdown)
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 2, in template
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'def'.
```

without "{% %}" it also doesn't work. (just rendered as generic text)

**Comment by fralau** [comment]
There is a little misunderstanding: that code must go in a `main.py` file in the same directory as your `mkdocs.yaml` file.

**Comment by slookin** [comment]
ohh... it is not easy.

main.py without "define_env" doesn't work at all
`NameError: No valid function found in module 'main'`

should "on_post_page_macros" will be inside "define_env" or a separed one?

my main.py right now:

```
def define_env(env):
  def on_post_page_macros(env):
    """
    Actions to be done after macro interpretation,
    just before the markdown is generated
    """
    env.page.meta['git'] = env.variables.git


def on_post_page_macros(env):
    """
    Actions to be done after macro interpretation,
    just before the markdown is generated
    """
    env.page.meta['git'] = env.variables.git

```

Template is:
```
<hr>
<div class="md-source-date">
  <small>
    {% if page.meta.git_revision_date_localized %}
      {{ label }}: {{ page.meta.git_revision_date_localized }} /version {{page.meta.git.tag}}
    {% elif page.meta.revision_date %}
      {{ label }}: {{ page.meta.revision_date }}
    {% endif %}
  </small>
</div>

```

logs:
`INFO    -  [macros] - Found external Python module 'main' in: /builds/...`
...
`jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'git'`

**Comment by fralau** [comment]
Much better: Sure, there must be a `define_env()` function, but it can do nothing:

```python
def define_env(env):
    pass
```

In principle, the `page` attribute of `env` is only available  in the `on_xxx_page_macros()`.

The log confirms that it found the `main.py` module. 

For debugging purposes, could you display the whole `page.meta` log?

**Comment by slookin** [comment]
it doesn't work. Look like **on_post_page_macros** never called. 

main.py

```
def define_env(env):
  print("! define_env " + str(env))
  pass

def on_post_page_macros(env):
  """
  Actions to be done after macro interpretation,
  just before the markdown is generated
  """
  print("! on_post_page_macros " + str(env))
  env.page.meta['git'] = env.variables.git

```

logs:
```
INFO    -  [macros] - Macros arguments: {'module_name': 'main', 'modules': [], 'include_dir': '', 'include_yaml': [], 'j2_block_start_string': '', 'j2_block_end_string': '', 'j2_variable_start_string': '', 'j2_variable_end_string': '', 'verbose': True}
DEBUG   - [macros] - Project dir '... '
INFO    -  macros] - Found external Python module 'main' in:

! define_env <mkdocs_macros.plugin.MacrosPlugin object at 0x03C41DF0>

DEBUG   -  [macros] - Variables: ['extra', 'config', 'environment', 'plugin', 'git', 'context', 'macros_info', 'now', 'fix_url', 'social']
INFO    -  [macros] - Extra variables (config file):['social']
DEBUG   -  [macros] - Content of extra variables (config file): {'social': [{'icon': 'fontawesome/brands/gitlab', 'link': '....'}]}
INFO    -  [macros] - Extra filters (module): ['pretty']
DEBUG   -  [macros] - Docs directory: ...
DEBUG   -  [macros] - Includes directory  ...

DEBUG   -  Reading markdown pages.
DEBUG   -  Reading: index.md

DEBUG   -  Building markdown pages.
DEBUG   -  Building page index.md
```

output on page (template has: {{page.meta}} ):
`{'git_revision_date_localized': 'January 20, 2021'}`

**Comment by slookin** [comment]
Solved without macros-plugin.
(using environment variable in git pipeline and via python/object/apply:os.getenv in mkdocs.yml)
