### ISSUE TITLE
0.5.4 on pypi?

### ISSUE THREAD

**Issue by emeraldMaster** [fralau/mkdocs_macros_plugin#65]
Hey, I found your plugin very helpful, thank you so much! Any plans to publish 0.5.4 on PyPI?

**Comment by fralau** [comment]
Oops, it would be time, wouldn't it?

Sorry for the oversight.

**Comment by fralau** [comment]
🚀  [V. 5.5 is tagged,](https://github.com/fralau/mkdocs_macros_plugin/releases/tag/v0.5.5) and [uploaded to pypi.](https://pypi.org/project/mkdocs-macros-plugin/) 

@emeraldMaster Let me know if it works for you?

**Comment by fralau** [comment]
@emeraldMaster Let me know if this solved the issue for you?

**Comment by emeraldMaster** [comment]
It works perfectly, thank you!
