### ISSUE TITLE
Fail the build when there are errors

### ISSUE THREAD

**Issue by burimshala** [fralau/mkdocs_macros_plugin#67]
Pages with errors that have side effect free code will produce un-recoverable errors on documentation pages so being able to fail the build and go back to fix the error would be very helpfull.

**Comment by fralau** [comment]
@burimshala Thanks for this point, which is quite important.

I would need more information on what you are observing. Is this something that has to do with mkdocs-macros specifically, or with mkdocs in general?

[Normally an execution error in a macro breaks the page (which makes sense), but not the server.]
