### ISSUE TITLE
Possible to use front-matter?

### ISSUE THREAD

**Issue by dcode** [fralau/mkdocs_macros_plugin#8]
I'd really like to use page-specific [front-matter](https://www.mkdocs.org/user-guide/writing-your-docs/#meta-data). In the actual MkDocs template, this data is provided via the dictionary `page.metadata`. Is it possible to access this from the `mkdocs_macros_plugin`?

When I run `mkdocs serve` all I get from the plugin is:
```
No module found.
Variables: {}
```

I didn't define any `extra` or custom python module, but even using `{% set foo='bar' %}` in the page doesn't do anything.

I'm using mkdocs, version 1.0.4 and mkdocs-macros-plugin, version 0.2.4.

Thanks!

**Comment by fralau** [comment]
Just to be sure: are you experiencing an issue with using the YAML front page?
Or do you think that it is failing because you do not have a module declared?
