### ISSUE TITLE
Include files in variables

### ISSUE THREAD

**Issue by briankchan** [fralau/mkdocs_macros_plugin#80]
[The source code includes a commented-out line for exposing mkdocs's `files`](https://github.com/fralau/mkdocs_macros_plugin/blob/f4ad1a139763818f8dfc099dd03b5c12999c0d4f/mkdocs_macros/plugin.py#L570).

It would be nice to enable this so that we can write macros that check for the existence of files; e.g., a macro to mark a link as disabled if its target doesn't exist.

**Comment by fralau** [comment]
That sounds like a good use case. 🤔 

Have you had the opportunity to look at the ins and outs? Any considerations, e.g. about security?

And I'm happy that someone read the code 😄

**Comment by briankchan** [comment]
I think the only weird thing that could come up is potentially odd behavior if macros mutate `files` during template rendering (especially to add/remove documentation pages), but that's not really a sensible thing to do in the first place.

As far as security is concerned, it shouldn't be much different from exposing `nav`, since pages in `nav` also have access to mkdocs's file objects.

**Comment by fralau** [comment]
You convinced me. 🙂

**Comment by fralau** [comment]
For the documentation, I'm not sure how to advise users on how to use that object. Would you be able to help me with that?

**Comment by briankchan** [comment]
It might be best to just say that it's the same `files` object available in certain [mkdocs events](https://www.mkdocs.org/user-guide/plugins/#events) and then point users to the mkdocs source code for `Files`, since mkdocs itself doesn't seem to provide any more documentation than that.

**Comment by fralau** [comment]
Thanks! I also raised the issue under mkdocs-discussions: https://github.com/mkdocs/mkdocs/discussions/2375
