### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by mondeja** [fralau/mkdocs_macros_plugin#82]
Please, a changelog would be very useful for packages that depend on the mkdocs_macros_plugin. Could you add one? Thanks!

**Comment by fralau** [comment]
@mondeja What would like to see in the changelog? Could you give me a couple of examples you consider virtuous?

**Comment by fralau** [comment]
I did a litle homework and found this: https://keepachangelog.com/en/1.0.0/

Is that a good starting point?

**Comment by mondeja** [comment]
> Could you give me a couple of examples you consider virtuous?

For example [mkdocs-material](https://github.com/squidfunk/mkdocs-material/blob/master/CHANGELOG), one based on Github Releases like [sphinx-github-changelog](https://github.com/ewjoachim/sphinx-github-changelog/releases) or RST included inside documentation like [tox](https://github.com/tox-dev/tox/blob/3.23.0/docs/changelog.rst). Really virtuousism is not something that I value in a history of changes, I just want to know what has changed to make sure that I don't break nothing updating the dependency.

So you understand the problem, when [dependabot updates mkdocs-macros-plugin](https://github.com/mondeja/http-request-codegen/pull/64), it doesn't include the changes, just the commits, but for other libraries that [includes release notes or changelog files](https://github.com/mondeja/http-request-codegen/pull/69) you can see that dependabot includes a section with the notes for the release and I can see easily what has changed.

What would like to see in the changelog?

What has changed for each release, what has been fixed...

**Comment by mondeja** [comment]
> Is that a good starting point?

Sure. Just a `CHANGELOG.md` file at the root of the project following that format would be worth :+1:

**Comment by fralau** [comment]
@mondeja OK, it doesn't seem to much to ask. I like mkdocs-material as a project (and generally what @squidfunk does), so I will gladly follow that pattern.

Rather than starting a project to install first a self-cleaning, Internet-connected factory, wouldn't it be the best if I started by humbly typing some info into that file, with my own two hands?

**Comment by mondeja** [comment]
> Rather than starting a project to install first a self-cleaning, Internet-connected factory, wouldn't it be the best if I started by humbly typing some info into that file, with my own two hands?

Yes, it would be probably the best starting point, maybe adding the new changes for 0.5.5

**Comment by fralau** [comment]
@mondeja Solved in 456ead7.

Would that work?

**Comment by mondeja** [comment]
Yep, thank you! :pray:
