### ISSUE TITLE
Issue with mkdocs material rendering connected to the macros plugin in the latest update

### ISSUE THREAD

**Issue by AntonKInv** [fralau/mkdocs_macros_plugin#84]
Hello Fralau,

First and foremost, thank you very much for your brilliant and versatile mkdocs Macros plugin! We've been using it for many months.
There is a macros plugin issue that emerged some time ago that I need to report. Presumably, it is caused by an incompatibility between the latest Mkdocs or Material theme version and the Macros plugin.

The latest configuration that worked well was as follows:
Mkdocs==1.1
Mkdocs-material==7.0.6
Mkdocs-macros-plugin==0.4.4

If Mkdocs gets updated to version 1.2, on pages generation we get broken layouts, as if the Material theme does not get applied:

![layout](https://user-images.githubusercontent.com/44772984/118972699-81839e00-b979-11eb-9f48-8428c9a55a51.png)

If we disable the macros plugin in mkdocs.yml file, rendering works as expected.

Please let us know if there might be a workaround or a fix.
Thank you in advance!

**Comment by fralau** [comment]
That is odd... I am using mkdocs 1.1.2 and mkdocs-material 7.0.6. without any problem.

Is your project using other plugins that could interfere? Or else, is there some macro or action in the `main.py`that could interfere?

Perhaps you could give the relevant parts of your `mkdocs.yml` (plugins, extensions, etc.).

**Comment by AntonKInv** [comment]
Hi. Thank you for your response. No, there is not much in the configuration. We've checked this on two clean PCs and we reproduced the issue on both, we also tried it without mkdocs custom_dir: overrides

plugins:
    - macros
    - search:
         method: strict
         separator: '[\s\-\.]+'

markdown_extensions:
    - smarty
    - toc:
        permalink: True
        separator: "_"
    - sane_lists
    - tables
    - meta
    - fenced_code
    - admonition
    - footnotes
    - fontawesome_markdown

theme:
  name: material
  custom_dir: overrides
  language: 'en'
  logo: 'assets/images/white.svg'
  palette:
    primary: 'green'
    accent: 'blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: 'assets/images/icon.ico'
  features:
    - search.highlight
    - search.suggest
    - search.share


The full config:
![image](https://user-images.githubusercontent.com/44772984/119274205-72ba1700-bc17-11eb-9041-c9b9665634bb.png)

**Comment by fralau** [comment]
Hmm... 🤔 I don't think that the culprit is either material or macros-plugin, but that something else is interfering.

Off the bat: try to declare the search plugin _before_ the macros plugin in your config file? (According to the documentation, the declaration should be in that order).

Or, just to "wiggle" a little, try to remove the search plugin and see whether it works? Or to remove the arguments from the search plugin? 

Or else, try to remove everything but mkdocs-material and mkdocs-macros, and try to rebuild from there?

**Comment by AntonKInv** [comment]
Hi again. Thank you for the tips! We've found the cause, it was our custom mkdocs overrides configuration.
Sorry for the false alarm.
