### ISSUE TITLE
Error when enabling plugin 'macros': 'LiveReloadServer' object has no attribute 'watcher'

### ISSUE THREAD

**Issue by edgarcamilocamacho** [fralau/mkdocs_macros_plugin#86]
Hello.

Using:

- Linux Mint 20.1 Ulyssa
- Python 3.8.5 (native)
- mkdocs 1.2 installed from pip3
- tested with macros-plugin installed from pip3 (0.5.5) and installed from the github repo (0.5.11)

I am trying to enable the **macros** plugin. This is my `mkdocs.yml` file:

``` yaml
site_name: Testing Page

site_url: https://example.com/

theme:
  name: material

plugins:
  - macros

markdown_extensions:
    - pymdownx.highlight:
        use_pygments: true
    - codehilite
    - pymdownx.superfence
...
```

But I get the following error when building:

```
INFO     -  Building documentation...
INFO     -  [macros] - Macros arguments: {'module_name': 'main', 'modules': [],
            'include_dir': '', 'include_yaml': [], 'j2_block_start_string': '',
            'j2_block_end_string': '', 'j2_variable_start_string': '', 'j2_variable_end_string':
            '', 'verbose': False}
INFO     -  [macros] - Extra filters (module): ['pretty']
INFO     -  Cleaning site directory
INFO     -  Documentation built in 0.38 seconds
Traceback (most recent call last):
  File "/home/camilo/.local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/camilo/.local/lib/python3.8/site-packages/mkdocs/__main__.py", line 173, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, **kwargs)
  File "/home/camilo/.local/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 78, in serve
    server = config['plugins'].run_event('serve', server, config=config, builder=builder)
  File "/home/camilo/.local/lib/python3.8/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/home/camilo/.local/lib/python3.8/site-packages/mkdocs_macros/plugin.py", line 600, in on_serve
    builder = list(server.watcher._tasks.values())[0]["func"]
AttributeError: 'LiveReloadServer' object has no attribute 'watcher'
```

I get the same error if I use other themes and if I disable extensions.

**Comment by Lucartas** [comment]
see this for an explanation: https://github.com/mkdocs/mkdocs/issues/2448
manually patching along the lines of https://github.com/mkdocstrings/mkdocstrings/pull/294 seems to work

**Comment by fralau** [comment]
@Lucartas Thanks! So, that would be an mkdocs issue?

@edgarcamilocamacho If you comment out the macros plugin, do you get the same error?

**Comment by ijmitch** [comment]
There's a description about the effects on on_serve in the [mkdocs 1.2 release notes](https://www.mkdocs.org/about/release-notes/#backward-incompatible-changes-in-12).

( I have tested a minimal mkdocs with and without the macros plugin and it only happens with it enabled. )

**Comment by fralau** [comment]
I issued an emergency fix (4bf847b3), version 0.5.12.

Let me know if that works for you (no bug and the watch list works correctly)?

**Comment by ijmitch** [comment]
0.5.12 has stopped the failure for me (macos Catalina, Python 3.9 and Mkdocs 1.2), but I can't really say with certainty if any/all the scenarios for the watch list are working.

**Comment by edgarcamilocamacho** [comment]
@fralau 0.5.12 worked perfectly for me. Thanks very much for the incredibly fast response and solution!!

**Comment by jaceklaskowski** [comment]
How to install the fix (tagged as [0.5.12](https://github.com/fralau/mkdocs_macros_plugin/releases/tag/v0.5.12)) using `requirements.txt` file? Why is 0.5.12 not a release?

**Comment by ijmitch** [comment]
@jaceklaskowski yeah... `pip install git+https://github.com/fralau/mkdocs_macros_plugin` was what worked for me (just letting it pick up the latest).

**Comment by timvink** [comment]
> Let me know if that works for you (no exception and the watch list works correctly)?

Same error, and your fix works. Thanks!

**Comment by edgarcamilocamacho** [comment]
@fralau should I close the issue?

**Comment by fralau** [comment]
In principle yes. But I'd like to confirm that the [watch mechanism for additional pages (when including other directories)](https://mkdocs-macros-plugin.readthedocs.io/en/latest/advanced.html#changing-the-directory-of-the-includes) still works.

Anyone?

**Comment by fralau** [comment]
Test passed ✅ 

(The `test` directory contains a `module` test project, where an `include` directory has been specified, aside of the `doc`one. It works, since startinkg `mkdocs serve` and modifying `include/foo.md` triggers a "reload" log message on the console). 

If no one has any objections, let's 🚀 and deploy it on pypi?

**Comment by fralau** [comment]
New version [0.5.12 released on pypi](https://pypi.org/project/mkdocs-macros-plugin/0.5.12/).
