### ISSUE TITLE
broken link on user guide section

### ISSUE THREAD

**Issue by CrispyDrone** [fralau/mkdocs_macros_plugin#89]
The link to a more detailed explanation of macros on https://mkdocs-macros-plugin.readthedocs.io/en/latest/pages.html#2-macro is broken.

**Comment by fralau** [comment]
Thanks 👍  

A number of internal links had been incorrectly inserted; they worked with `mkdocs serve` (but it had been accidental, see [issue on mkdocs](https://github.com/mkdocs/mkdocs/issues/2456)).

**Comment by fralau** [comment]
Fixed with #90

**Comment by fralau** [comment]
This is a fix on the documentation (`webdoc` directory).
