### ISSUE TITLE
Using a source file containing a yaml list

### ISSUE THREAD

**Issue by akhmerov** [fralau/mkdocs_macros_plugin#96]
I am switching an existing repo to mkdocs. For historical reason, my data is stored as a list in the root of a yaml file. Currently, when a file is loaded, `update(self.variables, content)` is called. This naturally fails if `content` is a list. Since this yaml format is used in several places throughout my codebase, I would prefer to keep it as is.

Therefore I have two questions:

1. Is there a workaround in the current version of the macros plugin, which would allow to load yaml files containing lists?
2. Would it be desirable to be able to load yaml content other than dictionaries, for example by putting them in a dictionary `{filename: content}`

Thanks for the powerful plugin!

**Comment by akhmerov** [comment]
Hmm, another alternative for supporting loading of arbitrary yaml data would be to extend the specification for `include_yaml` to allow dictionaries as well as lists:

```yaml
include_yaml:
  - data/file1.yml
  - key: data/file2.yml
```

**Comment by fralau** [comment]
@akhmerov That sounds like an interesting use case!

Could you give me an example of how your yaml file would look like, and what you would like to do with it?

**Comment by akhmerov** [comment]
It's https://github.com/virtualscienceforum/virtualscienceforum/blob/master/talks.yml, and it's in a repo for hosting online talks.

**Comment by akhmerov** [comment]
See #97 for a possible resolution.

**Comment by akhmerov** [comment]
And here's how it'd look in use: [mkdocs.yml](https://github.com/virtualscienceforum/virtualscienceforum/blob/78f451d5ea773e659d2ee9e665d6cc70c89062b0/mkdocs.yml#L51-L52). Works like a charm.

**Comment by fralau** [comment]
I get the point: it's pretty.

Let me check further on this.

**Comment by akhmerov** [comment]
I wouldn't go as far as to say elegant, but it's backwards-compatible, and better for interoperability with other tooling since it allows to load *any* data into the template context without format restrictions.
