### ISSUE TITLE
Cannot reassign env.raw_markdown property

### ISSUE THREAD

**Issue by sgilson** [fralau/mkdocs_macros_plugin#98]
Based on the docs here: https://github.com/fralau/mkdocs_macros_plugin/blame/master/webdoc/docs/advanced.md#L657-L659, it sounds like users have the opportunity to modify the interpreted markdown using the raw_markdown property, but attempting to reassign the property causes an AttributeError because it only has a getter: https://github.com/fralau/mkdocs_macros_plugin/blob/master/mkdocs_macros/plugin.py#L224.

I'd be willing to contribute a change to introduce a setter for the property.

The easy workaround is to instead modify env._raw_markdown, but this should probably not be encouraged.

**Comment by fralau** [comment]
Good point... yes, you are welcome to make a PR!
